name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  compile:
    name: Compile the project
    runs-on: self-hosted

    steps:
    - name: Checkout the project
      uses: actions/checkout@v4
        
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Install Maven
      run: sudo apt install maven -y

    - name: Build with Maven
      run: mvn compile

  security_check:
    name: Security check with Trivy
    runs-on: self-hosted
    needs: compile

    steps:
    - name: Checkout the Project
      uses: actions/checkout@v4 
      
    - name: Install Trivy 
      run: |
        sudo apt-get install wget gnupg
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
        echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update -y
        sudo apt-get install trivy -y

    - name: Run Trivy here 
      run: |
        trivy fs --format table -o trivy-scan-report.json .

    - name: Gitleaks Installation
      run: sudo apt install gitleaks -y

    - name: Scan the code with Gitleaks
      run: gitleaks detect source . -r gitleaks-report.json 


  test:
    name: Test Unit Cases 
    runs-on: self-hosted
    needs: compile

    steps:
     - name: Checkout the project
       uses: actions/checkout@v4
  
     - name: Setup JDK 17
       uses: actions/setup-java@v4
       with:
         java-version: '17'
         distribution: 'temurin'
  
     - name: Run Unit Test Cases
       run: mvn test

  sonar_scan:
    name: SOnarQube Scan
    runs-on: self-hosted

    steps: 
    - name: Checkout the project
      uses: actions/checkout@v4
  
    - name: Setup JDK 17
      uses: actions/setup-java@v4
      with:
       java-version: '17'
       distribution: 'temurin' 

    - name: Build Project
      run: mvn package

    - name: Checkout the project once again
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # SonarQube Scan
    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v5.0.0
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}

    # SonarQube Quality Gate Check
    - name: SonarQube Quality Gate Check
      uses: sonarsource/sonarqube-quality-gate-action@master
      with:
        pollingTimeoutSec: 600
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
      

      
      
